In [1]:
import numpy as np

def create_zero_matrix(value=0):
    return np.full((3, 3), value)

matrix = create_zero_matrix()
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

In [4]:
import pandas as pd
pd.Series([1, 2, 3,4 ])

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
import pandas as pd

data = [[1, 444, "abc"],
        [2, 555, "def"],
        [3, 666, "ghi"],
        [4, 444, "xyz"]]

df = pd.DataFrame(data, columns=['col1', 'col2', 'col3'])

print(df)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [9]:
import pandas as pd

data = [[1, 444, "abc"],
        [2, 555, "def"],
        [3, 666, "ghi"],
        [4, 444, "xyz"]]

df = pd.DataFrame(data)

df.columns = ['ip', 'salary', 'depart']
df.index = ['s', 'm', 't', 'u']

print(df)

   ip  salary depart
s   1     444    abc
m   2     555    def
t   3     666    ghi
u   4     444    xyz

In [10]:
df.dtypes

ip        int64
salary    int64
depart      str
dtype: object

In [11]:
df.ip.dtype

dtype('int64')

In [12]:
df.salary.dtype

dtype('int64')

In [13]:
df.depart.dtype

In [15]:
df['salary'] = df['salary'].astype(int)

In [26]:
data = [[1, 444, "abc"],
        [2, 555, "def"],
        [3, 666, "ghi"],
        [4, 444, "xyz"]]
df.depart.unique()
display(df.head(3))
display(df.tail(2))
print(df.depart.nunique())

   ip  salary depart
s   1     444    abc
m   2     555    def
t   3     666    ghi

   ip  salary depart
t   3     666    ghi
u   4     444    xyz

4

In [27]:
df["salary"].max()

np.int64(666)

In [28]:
df["salary"].min()

np.int64(444)

In [30]:
def get_range_of_salary(df):
	return df["salary"].max() - df["salary"].min()
print(get_range_of_salary(df))

222

In [34]:
df.salary.value_counts()

salary
444    2
555    1
666    1
Name: count, dtype: int64

In [36]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, s to u
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ip      4 non-null      int64
 1   salary  4 non-null      int64
 2   depart  4 non-null      str
dtypes: int64(2), str(1)
memory usage: 316.0 bytes

In [41]:
df["salary"].values

array([444, 555, 666, 444])

In [42]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [43]:
df.replace(555, "sohila")

   ip  salary depart
s   1     444    abc
m   2  sohila    def
t   3     666    ghi
u   4     444    xyz