In [1]:
import numpy as np

def create_zero_matrix(value=0):
    return np.full((3, 3), value)

matrix = create_zero_matrix()
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

In [4]:
import pandas as pd
pd.Series([1, 2, 3,4 ])

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
import pandas as pd

data = [[1, 444, "abc"],
        [2, 555, "def"],
        [3, 666, "ghi"],
        [4, 444, "xyz"]]

df = pd.DataFrame(data, columns=['col1', 'col2', 'col3'])

print(df)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [9]:
import pandas as pd

data = [[1, 444, "abc"],
        [2, 555, "def"],
        [3, 666, "ghi"],
        [4, 444, "xyz"]]

df = pd.DataFrame(data)

df.columns = ['ip', 'salary', 'depart']
df.index = ['s', 'm', 't', 'u']

print(df)

   ip  salary depart
s   1     444    abc
m   2     555    def
t   3     666    ghi
u   4     444    xyz

In [10]:
df.dtypes

ip        int64
salary    int64
depart      str
dtype: object

In [11]:
df.ip.dtype

dtype('int64')

In [12]:
df.salary.dtype

dtype('int64')

In [13]:
df.depart.dtype

In [15]:
df['salary'] = df['salary'].astype(int)

In [26]:
data = [[1, 444, "abc"],
        [2, 555, "def"],
        [3, 666, "ghi"],
        [4, 444, "xyz"]]
df.depart.unique()
display(df.head(3))
display(df.tail(2))
print(df.depart.nunique())

   ip  salary depart
s   1     444    abc
m   2     555    def
t   3     666    ghi

   ip  salary depart
t   3     666    ghi
u   4     444    xyz

4

In [27]:
df["salary"].max()

np.int64(666)

In [28]:
df["salary"].min()

np.int64(444)

In [30]:
def get_range_of_salary(df):
	return df["salary"].max() - df["salary"].min()
print(get_range_of_salary(df))

222

In [34]:
df.salary.value_counts()

salary
444    2
555    1
666    1
Name: count, dtype: int64

In [36]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, s to u
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ip      4 non-null      int64
 1   salary  4 non-null      int64
 2   depart  4 non-null      str
dtypes: int64(2), str(1)
memory usage: 316.0 bytes

In [41]:
df["salary"].values

array([444, 555, 666, 444])

In [42]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [43]:
df.replace(555, "sohila")

   ip  salary depart
s   1     444    abc
m   2  sohila    def
t   3     666    ghi
u   4     444    xyz

In [2]:
import pandas as pd
df = pd.read_csv('Titanic.csv')
df.drop(['PassengerId','Name','Ticket' ], axis = 1 ,inplace = True)

In [3]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [4]:
import pandas as pd
df = pd.read_csv('Titanic.csv')
df.drop(['PassengerId', 'Name', 'Ticket'], axis = 1, inplace = True)

In [5]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [6]:
def drop_columns(df, columns):
    return df.drop(columns=columns)

In [45]:
DROP_CLO = ['PassengerId', 'Name', 'Ticket']

def drop_columns(df, columns):
    return df.drop(columns=columns, errors='ignore')

drop_columns(df, DROP_CLO)

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [46]:
dtypes = df.dtypes
df.nunique()

Survived      2
Pclass        3
Sex           2
Age          88
SibSp         7
Parch         7
Fare        248
Cabin       147
Embarked      3
dtype: int64

In [47]:
dtypes = df.dtypes
n_unique = df.nunique()
pd.DataFrame({"Dtypes ": dtypes, "N_unique ": n_unique}).T

          Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes       int64  int64  str  float64  int64  int64  float64   str      str
N_unique         2      3    2       88      7      7      248   147        3

In [54]:
df.isnull()

     Survived  Pclass    Sex    Age  SibSp  Parch   Fare  Cabin  Embarked
0       False   False  False  False  False  False  False   True     False
1       False   False  False  False  False  False  False  False     False
2       False   False  False  False  False  False  False   True     False
3       False   False  False  False  False  False  False  False     False
4       False   False  False  False  False  False  False   True     False
..        ...     ...    ...    ...    ...    ...    ...    ...       ...
886     False   False  False  False  False  False  False   True     False
887     False   False  False  False  False  False  False  False     False
888     False   False  False   True  False  False  False   True     False
889     False   False  False  False  False  False  False  False     False
890     False   False  False  False  False  False  False   True     False

[891 rows x 9 columns]

In [55]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [56]:
null = df.isnull().sum()
ratio = null / 891
ratio

Survived    0.000000
Pclass      0.000000
Sex         0.000000
Age         0.198653
SibSp       0.000000
Parch       0.000000
Fare        0.000000
Cabin       0.771044
Embarked    0.002245
dtype: float64